console("123");
const abc = 123;
console.log(abc);
const def = 456;
console.log(def);
const name = "hello";
console.log("master创建内容");
console.log("CodeMorty修改内容");
console.log("CodeMorty修改内容2");
console.log("CodeMorty修改内容3");
